version: "3"
services:
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - test-automation-setup
  
  chrome:
    container_name: chrome-node
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - test-automation-setup    
    
  firefox:
    container_name: firefox-node
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - test-automation-setup

  mvn-tests-chrome:
    container_name: mvn_tests_chrome
    image: nberzins/mvn_tests:latest
    depends_on:
      - chrome
    networks: 
      - test-automation-setup
    command: bash -c "mvn clean test -Dbrowser=chrome -DgridURL=selenium-hub:4444 && mvn io.qameta.allure:allure-maven:report && rm -rf allure_test_results/* && cp -r target/site/allure-maven-plugin allure_test_results"
    volumes:
      - $PWD/allure_test_results:/docker/allure_test_results/

  mvn-tests-firefox:
    container_name: mvn_tests_firefox
    image: nberzins/mvn_tests:latest
    depends_on:
      - firefox
    networks: 
      - test-automation-setup
    command: bash -c "mvn clean test -Dbrowser=firefox -DgridURL=selenium-hub:4444 && mvn io.qameta.allure:allure-maven:report && rm -rf allure_test_results/* && cp -r target/site/allure-maven-plugin allure_test_results"
    volumes:
      - $PWD/allure_test_results:/docker/allure_test_results/
    
networks: 
  test-automation-setup:
    external: true